name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Compile Java and run tests
      run: |
        mkdir -p target/classes
        mkdir -p target/test-classes
        javac -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" -d target/classes $(find src/main/java -name "*.java")
        javac -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:target/classes" -d target/test-classes $(find src/test -name "*.java")
        java -cp "target/test-classes:target/classes:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore test.CorpoHumanoTest